spring:
  application:
    name: meldora
  graphql:
    graphiql:
      enabled: true
      schema:
        locations: classpath:graphql/,classpath:tmdb/
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  token:
    access-secret-key: ${JWT_ACCESS_SECRET_KEY}
    access-secret-key-expiration: ${JWT_ACCESS_SECRET_EXPIRATION}
    refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
    refresh-secret-key-expiration: ${JWT_REFRESH_SECRET_EXPIRATION}
  cache:
    config:
      cache-expiration: ${CACHE_EXPIRATION_IN_MINUTES}

server:
  http2:
    enabled: true

tmdb:
  config:
    read-access-key: ${TMDB_READ_ACCESS_KEY}
    api-key: ${TMDB_API_KEY}
    base-url: ${TMDB_BASE_URL}

spotify:
  config:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    base-url: ${SPOTIFY_BASE_URL}

